# Usa l'immagine ufficiale Node.js come base
FROM node:20.18.0

# Imposta la directory di lavoro all'interno del container
WORKDIR /usr/src/app

# Copia il file package.json e yarn.lock nella directory di lavoro
COPY package.json yarn.lock ./

# Installa Yarn nella versione 4.5.0
RUN corepack enable && \
    corepack prepare yarn@4.5.0 --activate

# Installa le dipendenze dell'applicativo
RUN yarn install --frozen-lockfile

# Copia il resto del codice dell'applicativo nella directory di lavoro
COPY . .

# Esponi la porta su cui Vite serve l'applicazione (di default 5173)
EXPOSE 5173

# Comando di default per avviare il server di sviluppo di Vite
CMD ["yarn", "dev", "--host"]
